// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package metadataschema

import "encoding/json"
import "fmt"
import "unicode/utf8"

type ArtifactMetadataV1 struct {
	// CompressedSize corresponds to the JSON schema field "compressed_size".
	CompressedSize int `json:"compressed_size" yaml:"compressed_size" mapstructure:"compressed_size"`

	// FileName corresponds to the JSON schema field "file_name".
	FileName string `json:"file_name" yaml:"file_name" mapstructure:"file_name"`

	// SchemaVersion corresponds to the JSON schema field "schema_version".
	SchemaVersion int `json:"schema_version" yaml:"schema_version" mapstructure:"schema_version"`

	// Sloc corresponds to the JSON schema field "sloc".
	Sloc int `json:"sloc" yaml:"sloc" mapstructure:"sloc"`

	// TargetLanguage corresponds to the JSON schema field "target_language".
	TargetLanguage string `json:"target_language" yaml:"target_language" mapstructure:"target_language"`

	// UncompressedSize corresponds to the JSON schema field "uncompressed_size".
	UncompressedSize int `json:"uncompressed_size" yaml:"uncompressed_size" mapstructure:"uncompressed_size"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ArtifactMetadataV1) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["compressed_size"]; raw != nil && !ok {
		return fmt.Errorf("field compressed_size in ArtifactMetadataV1: required")
	}
	if _, ok := raw["file_name"]; raw != nil && !ok {
		return fmt.Errorf("field file_name in ArtifactMetadataV1: required")
	}
	if _, ok := raw["schema_version"]; raw != nil && !ok {
		return fmt.Errorf("field schema_version in ArtifactMetadataV1: required")
	}
	if _, ok := raw["sloc"]; raw != nil && !ok {
		return fmt.Errorf("field sloc in ArtifactMetadataV1: required")
	}
	if _, ok := raw["target_language"]; raw != nil && !ok {
		return fmt.Errorf("field target_language in ArtifactMetadataV1: required")
	}
	if _, ok := raw["uncompressed_size"]; raw != nil && !ok {
		return fmt.Errorf("field uncompressed_size in ArtifactMetadataV1: required")
	}
	type Plain ArtifactMetadataV1
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.CompressedSize {
		return fmt.Errorf("field %s: must be >= %v", "compressed_size", 0)
	}
	if utf8.RuneCountInString(string(plain.FileName)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "file_name", 1)
	}
	if plain.SchemaVersion != 1 {
		return fmt.Errorf("field %s: must be equal to %v", "schema_version", 1)
	}
	if 0 > plain.Sloc {
		return fmt.Errorf("field %s: must be >= %v", "sloc", 0)
	}
	if utf8.RuneCountInString(string(plain.TargetLanguage)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "target_language", 1)
	}
	if 0 > plain.UncompressedSize {
		return fmt.Errorf("field %s: must be >= %v", "uncompressed_size", 0)
	}
	*j = ArtifactMetadataV1(plain)
	return nil
}
