// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package flowschema

import "encoding/json"
import "fmt"

type CodeFlow struct {
	// ThreadFlows corresponds to the JSON schema field "thread_flows".
	ThreadFlows []ThreadFlow `json:"thread_flows" yaml:"thread_flows" mapstructure:"thread_flows"`
}

type CodeFlowStep struct {
	// CallerFunctionId corresponds to the JSON schema field "caller_function_id".
	CallerFunctionId CodeFlowStepCallerFunctionId `json:"caller_function_id" yaml:"caller_function_id" mapstructure:"caller_function_id"`

	// EndColumn corresponds to the JSON schema field "end_column".
	EndColumn *int `json:"end_column,omitempty,omitzero" yaml:"end_column,omitempty" mapstructure:"end_column,omitempty"`

	// EndLine corresponds to the JSON schema field "end_line".
	EndLine *int `json:"end_line,omitempty,omitzero" yaml:"end_line,omitempty" mapstructure:"end_line,omitempty"`

	// Message corresponds to the JSON schema field "message".
	Message *string `json:"message,omitempty,omitzero" yaml:"message,omitempty" mapstructure:"message,omitempty"`

	// ResolvedPath corresponds to the JSON schema field "resolved_path".
	ResolvedPath *string `json:"resolved_path,omitempty,omitzero" yaml:"resolved_path,omitempty" mapstructure:"resolved_path,omitempty"`

	// SourceLine corresponds to the JSON schema field "source_line".
	SourceLine *string `json:"source_line,omitempty,omitzero" yaml:"source_line,omitempty" mapstructure:"source_line,omitempty"`

	// StartColumn corresponds to the JSON schema field "start_column".
	StartColumn *int `json:"start_column,omitempty,omitzero" yaml:"start_column,omitempty" mapstructure:"start_column,omitempty"`

	// StartLine corresponds to the JSON schema field "start_line".
	StartLine *int `json:"start_line,omitempty,omitzero" yaml:"start_line,omitempty" mapstructure:"start_line,omitempty"`

	// Uri corresponds to the JSON schema field "uri".
	Uri string `json:"uri" yaml:"uri" mapstructure:"uri"`
}

type CodeFlowStepCallerFunctionId *string

// UnmarshalJSON implements json.Unmarshaler.
func (j *CodeFlowStep) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["caller_function_id"]; raw != nil && !ok {
		return fmt.Errorf("field caller_function_id in CodeFlowStep: required")
	}
	if _, ok := raw["uri"]; raw != nil && !ok {
		return fmt.Errorf("field uri in CodeFlowStep: required")
	}
	type Plain CodeFlowStep
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.EndColumn != nil && 1 > *plain.EndColumn {
		return fmt.Errorf("field %s: must be >= %v", "end_column", 1)
	}
	if plain.EndLine != nil && 1 > *plain.EndLine {
		return fmt.Errorf("field %s: must be >= %v", "end_line", 1)
	}
	if plain.StartColumn != nil && 1 > *plain.StartColumn {
		return fmt.Errorf("field %s: must be >= %v", "start_column", 1)
	}
	if plain.StartLine != nil && 1 > *plain.StartLine {
		return fmt.Errorf("field %s: must be >= %v", "start_line", 1)
	}
	*j = CodeFlowStep(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CodeFlow) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["thread_flows"]; raw != nil && !ok {
		return fmt.Errorf("field thread_flows in CodeFlow: required")
	}
	type Plain CodeFlow
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = CodeFlow(plain)
	return nil
}

type FlowV1 []CodeFlow

type ThreadFlow struct {
	// Steps corresponds to the JSON schema field "steps".
	Steps []CodeFlowStep `json:"steps" yaml:"steps" mapstructure:"steps"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ThreadFlow) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["steps"]; raw != nil && !ok {
		return fmt.Errorf("field steps in ThreadFlow: required")
	}
	type Plain ThreadFlow
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ThreadFlow(plain)
	return nil
}
